version: '3'
services:
  app:
    build: .
    container_name: main_app
    ports:
      - "3000:3000"
    restart: always
    links:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - JWT_SECRET=mi_clave_secreta
      - MONGODB_HOST=127.0.0.1
      - MONGODB_PORT=27017
      - MONGODB_DBNAME=users
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - /data/db
