version: '3'
services:
  app:
    build: .
    container_name: main_app
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - app_data:/app
    environment:
      - PORT=3000
      - JWT_SECRET=mi_clave_secreta
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DBNAME=users
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  app_data:
  mongo_data:
